#!/usr/bin/bash


BLUR=6
INVISIBLE=\#00000000

VERIFICATION_COLOUR=\#0A7CFF
WRONG_COLOUR=\#ff0a37

KEY_COLOUR=\#5C8DFF
BACKSPACE_COLOUR=\#429AFF

TIME_COLOUR=\#0A70FF
DATE_COLOUR=\#0060E6

BAR_COLOUR=\#5C8DFF


i3lock \
--clock \
--ignore-empty-password \
--redraw-thread \
--bar-indicator \
--no-modkeytext \
--blur=$BLUR \
\
--insidecolor=$INVISIBLE \
--insidevercolor=$INVISIBLE \
--insidewrongcolor=$INVISIBLE \
\
--verifcolor=$VERIFICATION_COLOUR \
--wrongcolor=$WRONG_COLOUR \
\
--ringcolor=$INVISIBLE \
--linecolor=$INVISIBLE \
--separatorcolor=$INVISIBLE \
\
--keyhlcolor=$KEY_COLOUR \
--bshlcolor=$BACKSPACE_COLOUR \
\
--timecolor=$TIME_COLOUR \
--datecolor=$DATE_COLOUR \
--greetercolor=\#FFFFFF \
\
--greetertext="Enter The Password To Unlock" \
--veriftext="Verifying..." \
--wrongtext="Wrong Password:(" \
--noinputtext="No Input" \
--locktext="Locking..." \
--lockfailedtext="Locking Failed!" \
\
--bar-color=$INVISIBLE \
--bar-count=100 \
--bar-position y+h \
--bar-direction 1 \
--bar-max-height=150 \
--bar-step=44 \
--bar-periodic-step=38 \
\
--timesize=60 \
--datesize=17 \
--greetersize=30
