#!/usr/bin/bash


BLUR=6
INVISIBLE=\#00000000

VERIFICATION_COLOUR=\#FABD2F
WRONG_COLOUR=\#FB4934

KEY_COLOUR=\#FE8019
BACKSPACE_COLOUR=\#E97501

TIME_COLOUR=\#FE7301
DATE_COLOUR=\#DA6301


i3lock \
--clock \
--ignore-empty-password \
--redraw-thread \
--bar-indicator \
--no-modkeytext \
--blur=$BLUR \
\
--verifcolor=$VERIFICATION_COLOUR \
--wrongcolor=$WRONG_COLOUR \
\
--ringcolor=$INVISIBLE \
--linecolor=$INVISIBLE \
--separatorcolor=$INVISIBLE \
\
--keyhlcolor=$KEY_COLOUR \
--bshlcolor=$BACKSPACE_COLOUR \
\
--timecolor=$TIME_COLOUR \
--datecolor=$DATE_COLOUR \
--greetercolor=\#FFFFFF \
\
--veriftext="Verifying..." \
--wrongtext="Wrong Password:(" \
--noinputtext="No Input" \
--locktext="Locking..." \
--lockfailedtext="Locking Failed!" \
\
--bar-color=$INVISIBLE \
--bar-count=100 \
--bar-position=y+h+50 \
--bar-direction=1 \
--bar-max-height=170 \
--bar-step=44 \
--bar-periodic-step=38 \
\
--timesize=60 \
--verifsize=40 \
--wrongsize=40 \
--datesize=17 \
\
--datestr="%Y, %b %d, %A"
